POST http://localhost:3000/api/admin/createNewAccount
Content-Type: application/json

{
    "username":"admin1",
    "password":"admin"
}

###
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

###
POST http://localhost:3000/api/admin/updatePandemicData
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTI4OTU5ZTNjODg3MzM5MjM1Nzc2ZTMiLCJpYXQiOjE2MzAwNTUxNjl9.EmL3s8eSheb9GLFqSUvQ3RlPYUFAxp-Gkfn7ixnLsdM

{
    "title":"Hello",
    "content":"Cap nhat tinh hinh dich ngay 27/8 ... 1"
}

###
GET http://localhost:3000/api/public/displayPandemicFullData

###
PUT http://localhost:3030/api/admin/updateAnalytics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTI4OTU5ZTNjODg3MzM5MjM1Nzc2ZTMiLCJpYXQiOjE2MzAzNDMwNTZ9.gUlWMg7CPS_8VeDCTOriuCgn3UVh2YjUzhF7wp-qq7s

{
    "position":"tpvinh",
    "total":5,
    "death":0,
    "cured":2
}

###
GET http://localhost:3030/api/admin/displayAccountList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTI4OTU5ZTNjODg3MzM5MjM1Nzc2ZTMiLCJpYXQiOjE2MzAzNDMwNTZ9.gUlWMg7CPS_8VeDCTOriuCgn3UVh2YjUzhF7wp-qq7s


###
DELETE http://localhost:3030/api/admin/deletePandemicData/abcdef1231231231231231
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTI4OTU5ZTNjODg3MzM5MjM1Nzc2ZTMiLCJpYXQiOjE2MzAzNDMwNTZ9.gUlWMg7CPS_8VeDCTOriuCgn3UVh2YjUzhF7wp-qq7s


###
POST http://localhost:3030/api/admin/createBlogPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTI4OTQ4YThmYjJmYzU0YzMyOTFkMjIiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjMwNjA3NDA3LCJleHAiOjE2MzEyMTIyMDd9.IFHPOEOenNwEhHhHme_DnjEZINxMUUd2CO_4czL9vwA

{
    "title":"Aloaloss",
    "content":"Huong dan cach phong dich"
}


###
POST http://localhost:3030/api/admin/createNEWS
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTI4OTQ4YThmYjJmYzU0YzMyOTFkMjIiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjMwNjA3NDA3LCJleHAiOjE2MzEyMTIyMDd9.IFHPOEOenNwEhHhHme_DnjEZINxMUUd2CO_4czL9vwA

{
    "title":"Vinh chi thi 16 tu 6/9",
    "content":"ABCXYZ"
}

###
DELETE http://localhost:3030/api/admin/deleteBlogPost/612dc91df01e64f200bb6d38
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTI4OTU5ZTNjODg3MzM5MjM1Nzc2ZTMiLCJpYXQiOjE2MzAwNTUxNjl9.EmL3s8eSheb9GLFqSUvQ3RlPYUFAxp-Gkfn7ixnLsdM

###
GET http://localhost:3030/api/public/displayNEWS


###
GET http://localhost:3030/api/public/displayBlogPost